### ISSUE TITLE
how come sometimes links are red in body text, some times not? Can it be red in both instances?

### ISSUE THREAD

**Issue by gvklooster** [redhousestudio/redhousestudio.github.io#18]
![screen shot 2018-01-05 at 15 04 54](https://user-images.githubusercontent.com/1320087/34612394-e99c5786-f229-11e7-89da-a488c6812846.png)
![screen shot 2018-01-05 at 15 04 48](https://user-images.githubusercontent.com/1320087/34612395-e9b495a8-f229-11e7-981c-643b66a97bfe.png)

**Comment by gvklooster** [comment]
it seems it is only *not* working in discography section text

the "About" works:
![screen shot 2018-01-05 at 19 47 41](https://user-images.githubusercontent.com/1320087/34623372-637c4c88-f251-11e7-9799-41bca5c930f9.png)

**Comment by faizanvahevaria** [comment]
@GFunkloostar 
http://redhouse.nl/testnew/discography.html

See this.
You did this in Design that's why I did it.

**Comment by gvklooster** [comment]
ok, well design-wise it is better to do it same for all. And specially the discography section has very important links so must be red.
