### ISSUE TITLE
misplaced social icons

### ISSUE THREAD

**Issue by gvklooster** [redhousestudio/redhousestudio.github.io#19]
![screen shot 2018-01-05 at 18 32 10](https://user-images.githubusercontent.com/1320087/34620734-c814c496-f246-11e7-9d7b-7a5c1cfdf559.png)
![screen shot 2018-01-05 at 18 31 50](https://user-images.githubusercontent.com/1320087/34620735-c8352600-f246-11e7-881c-b7ce01b63315.png)

**Comment by faizanvahevaria** [comment]
@GFunkloostar 

I think you solved the issue by using <br>

Right?
