### ISSUE TITLE
left and right borders of project thumbnails should be aligned to full width of frame.

### ISSUE THREAD

**Issue by gvklooster** [redhousestudio/redhousestudio.github.io#2]
![screen shot 2017-12-29 at 20 45 06](https://user-images.githubusercontent.com/1320087/34446243-ba33cbc8-ecd9-11e7-98fb-8e4c428a5a36.png)
![screen shot 2017-12-29 at 20 45 02](https://user-images.githubusercontent.com/1320087/34446244-ba4b95d2-ecd9-11e7-9e12-472f06e8df2d.png)
![screen shot 2017-12-29 at 20 44 41](https://user-images.githubusercontent.com/1320087/34446245-ba61f1a6-ecd9-11e7-866a-6c31e6b2a514.png)

**Comment by faizanvahevaria** [comment]
this is done.
Please close
@GFunkloostar
