### ISSUE TITLE
font in project frames should be "Roboto Mono"

### ISSUE THREAD

**Issue by gvklooster** [redhousestudio/redhousestudio.github.io#7]

**Comment by gvklooster** [comment]
![screen shot 2017-12-22 at 00 03 36](https://user-images.githubusercontent.com/1320087/34449037-3b7b2554-ecf4-11e7-884e-a6e1cb62c96f.png)

**Comment by gvklooster** [comment]
only in the (grey) project frames. Not on the project pages.
![screen shot 2018-01-01 at 21 19 19](https://user-images.githubusercontent.com/1320087/34470775-819fc7be-ef39-11e7-833c-65841adf79ee.png)

**Comment by gvklooster** [comment]
![screen shot 2018-01-02 at 16 07 00](https://user-images.githubusercontent.com/1320087/34488016-0e540cc2-efd7-11e7-988e-2121c39713e6.png)
![screen shot 2018-01-02 at 16 07 06](https://user-images.githubusercontent.com/1320087/34488021-1153c70a-efd7-11e7-92dc-61d349545cc9.png)

not correct

**Comment by gvklooster** [comment]
Text jumps in hover over layout. Can we prevent that?
![screen shot 2018-01-04 at 03 07 33](https://user-images.githubusercontent.com/1320087/34547584-7f44c04a-f0fc-11e7-8d2f-70d25b1e5ba3.png)
![screen shot 2018-01-04 at 03 04 01](https://user-images.githubusercontent.com/1320087/34547585-7f630b18-f0fc-11e7-9cc4-14e559ee4700.png)

**Comment by faizanvahevaria** [comment]
This is Done.
Please close.
@GFunkloostar

**Comment by gvklooster** [comment]
I still see 2 font sizes here. And while your at it, please remove the Roboto Mono Font and use the same font for the body text. Rather small size here.

![screen shot 2018-01-05 at 22 25 39](https://user-images.githubusercontent.com/1320087/34629323-02fbbfbc-f268-11e7-9da4-997518af948c.png)

And please reduce the spacing between the gray text and the red text with a few px. Because this is wrong:

![screen shot 2018-01-05 at 22 28 51](https://user-images.githubusercontent.com/1320087/34629332-0af34ec4-f268-11e7-9fc5-4a3041081702.png)
